-- 1. Tabla ROL
CREATE TABLE rol (
                     id_rol      BIGINT GENERATED BY DEFAULT AS IDENTITY,
                     nombre_rol  VARCHAR(100) NOT NULL,
                     descripcion TEXT,

                     CONSTRAINT pk_rol PRIMARY KEY (id_rol)
);

-- 2. Tabla USUARIO (Depende de ROL)
CREATE TABLE usuario (
                         id_usuario      BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         id_rol          BIGINT NOT NULL,
                         nombre_completo VARCHAR(160) NOT NULL,
                         credenciales    VARCHAR(255) NOT NULL,
                         estado          VARCHAR(20)  NOT NULL,

                         CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
                         CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES rol (id_rol)
);

-- 3. Tabla LECTOR (Depende de USUARIO)
CREATE TABLE lector (
                        id_lector      BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        id_usuario     BIGINT NOT NULL,
                        nro_lector     VARCHAR(40) NOT NULL,
                        datos_contacto VARCHAR(255),
                        fecha_registro DATE NOT NULL,

                        CONSTRAINT pk_lector PRIMARY KEY (id_lector),
                        CONSTRAINT fk_lector_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
                        CONSTRAINT uq_lector_usuario UNIQUE (id_usuario),
                        CONSTRAINT uq_lector_nro UNIQUE (nro_lector)
);

-- 4. Tabla MULTA (Depende de LECTOR)
CREATE TABLE multa (
                       id_sancion   BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       id_lector    BIGINT NOT NULL,
                       fecha_inicio DATE NOT NULL,
                       fecha_final  DATE,
                       motivo       VARCHAR(250) NOT NULL,
                       estado       VARCHAR(20)  NOT NULL,

                       CONSTRAINT pk_multa PRIMARY KEY (id_sancion),
                       CONSTRAINT fk_multa_lector FOREIGN KEY (id_lector) REFERENCES lector (id_lector)
);

-- 5. Tabla EDITORIAL
CREATE TABLE editorial (
                           id_editorial BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           nombre       VARCHAR(160) NOT NULL,

                           CONSTRAINT pk_editorial PRIMARY KEY (id_editorial)
);

-- 6. Tabla LIBRO (Depende de EDITORIAL)
CREATE TABLE libro (
                       id_libro         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       id_editorial     BIGINT NOT NULL,
                       titulo           VARCHAR(220) NOT NULL,
                       autor            VARCHAR(150) NOT NULL,
                       categoria        VARCHAR(100),
                       anio_publicacion INTEGER,

                       CONSTRAINT pk_libro PRIMARY KEY (id_libro),
                       CONSTRAINT fk_libro_editorial FOREIGN KEY (id_editorial) REFERENCES editorial (id_editorial)
);

-- 7. Tabla PRESTAMO (Depende de LECTOR y LIBRO)
CREATE TABLE prestamo (
                          id_prestamo               BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          id_lector                 BIGINT NOT NULL,
                          id_libro                  BIGINT NOT NULL,
                          fecha_salida              DATE NOT NULL,
                          fecha_prevista_devolucion DATE NOT NULL,
                          fecha_devolucion_real     DATE,
                          estado                    VARCHAR(20) NOT NULL,

                          CONSTRAINT pk_prestamo PRIMARY KEY (id_prestamo),
                          CONSTRAINT fk_prestamo_lector FOREIGN KEY (id_lector) REFERENCES lector (id_lector),
                          CONSTRAINT fk_prestamo_libro FOREIGN KEY (id_libro) REFERENCES libro (id_libro)
);

-- 8. Tabla RENOVACION (Depende de PRESTAMO)
CREATE TABLE renovacion (
                            id_renovacion        BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            id_prestamo          BIGINT NOT NULL,
                            fecha_renovacion     DATE NOT NULL,
                            nueva_fecha_prevista DATE NOT NULL,

                            CONSTRAINT pk_renovacion PRIMARY KEY (id_renovacion),
                            CONSTRAINT fk_renovacion_prestamo FOREIGN KEY (id_prestamo) REFERENCES prestamo (id_prestamo)
);

-- 9. Tabla RESERVA (Depende de LECTOR y LIBRO)
CREATE TABLE reserva (
                         id_reserva          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         id_lector           BIGINT NOT NULL,
                         id_libro            BIGINT NOT NULL,
                         fecha_reserva       DATE NOT NULL,
                         fecha_limite_retiro DATE NOT NULL,
                         estado              VARCHAR(30) NOT NULL,

                         CONSTRAINT pk_reserva PRIMARY KEY (id_reserva),
                         CONSTRAINT fk_reserva_lector FOREIGN KEY (id_lector) REFERENCES lector (id_lector),
                         CONSTRAINT fk_reserva_libro FOREIGN KEY (id_libro) REFERENCES libro (id_libro)
);