CREATE TABLE rol (
                     id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     nombre_rol VARCHAR(100) NOT NULL,
                     descripcion TEXT
);

CREATE TABLE usuario (
                         id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         id_rol BIGINT NOT NULL,
                         nombre_completo VARCHAR(160) NOT NULL,
                         credenciales VARCHAR(255) NOT NULL,
                         estado VARCHAR(20) NOT NULL,

                         CONSTRAINT fk_usuario_rol
                             FOREIGN KEY (id_rol)
                                 REFERENCES rol(id_rol)
);

CREATE TABLE lector (
                        id_lector BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        id_usuario BIGINT UNIQUE,
                        nro_lector VARCHAR(50) NOT NULL,
                        datos_contacto VARCHAR(255) NOT NULL,
                        fecha_registro DATE NOT NULL,

                        CONSTRAINT fk_lector_usuario
                            FOREIGN KEY (id_usuario)
                                REFERENCES usuario(id_usuario)
);

CREATE TABLE autor (
                       id_autor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nombre VARCHAR(255) NOT NULL
);

CREATE TABLE editorial (
                           id_editorial BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nombre VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE libro (
                       id_libro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       titulo VARCHAR(255),
                       isbn VARCHAR(20) UNIQUE,
                       categoria VARCHAR(255),
                       anio_publicacion INTEGER,
                       id_editorial BIGINT NOT NULL,

                       CONSTRAINT fk_libro_editorial
                           FOREIGN KEY (id_editorial)
                               REFERENCES editorial(id_editorial)
);

CREATE TABLE libro_autor (
                             id_libro_autor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             id_libro BIGINT NOT NULL,
                             id_autor BIGINT NOT NULL,

                             CONSTRAINT fk_libro_autor_libro
                                 FOREIGN KEY (id_libro)
                                     REFERENCES libro(id_libro),

                             CONSTRAINT fk_libro_autor_autor
                                 FOREIGN KEY (id_autor)
                                     REFERENCES autor(id_autor),

                             CONSTRAINT uk_libro_autor
                                 UNIQUE (id_libro, id_autor)
);

CREATE TABLE ejemplar (
                          id_ejemplar BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          codigo VARCHAR(50) NOT NULL UNIQUE,
                          estado VARCHAR(30) NOT NULL,
                          id_libro BIGINT NOT NULL,

                          CONSTRAINT fk_ejemplar_libro
                              FOREIGN KEY (id_libro)
                                  REFERENCES libro(id_libro)
);

CREATE TABLE prestamo (
                          id_prestamo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          id_lector BIGINT NOT NULL,
                          id_ejemplar BIGINT NOT NULL,
                          fecha_prestamo DATE NOT NULL,
                          fecha_vencimiento DATE NOT NULL,
                          fecha_devolucion DATE,
                          estado VARCHAR(30) NOT NULL,

                          CONSTRAINT fk_prestamo_lector
                              FOREIGN KEY (id_lector)
                                  REFERENCES lector(id_lector),

                          CONSTRAINT fk_prestamo_ejemplar
                              FOREIGN KEY (id_ejemplar)
                                  REFERENCES ejemplar(id_ejemplar)
);

CREATE TABLE renovacion (
                            id_renovacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            id_prestamo BIGINT NOT NULL,
                            fecha_renovacion DATE NOT NULL,
                            nueva_fecha_vencimiento DATE NOT NULL,

                            CONSTRAINT fk_renovacion_prestamo
                                FOREIGN KEY (id_prestamo)
                                    REFERENCES prestamo(id_prestamo)
);

CREATE TABLE reserva (
                         id_reserva BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         id_lector BIGINT NOT NULL,
                         id_libro BIGINT NOT NULL,
                         fecha_reserva DATE NOT NULL,
                         fecha_limite_retiro DATE NOT NULL,
                         estado VARCHAR(30) NOT NULL,

                         CONSTRAINT fk_reserva_lector
                             FOREIGN KEY (id_lector)
                                 REFERENCES lector(id_lector),

                         CONSTRAINT fk_reserva_libro
                             FOREIGN KEY (id_libro)
                                 REFERENCES libro(id_libro)
);

CREATE TABLE sancion (
                         id_sancion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         id_lector BIGINT NOT NULL,
                         fecha_inicio DATE NOT NULL,
                         fecha_final DATE,
                         motivo VARCHAR(250) NOT NULL,
                         estado VARCHAR(20) NOT NULL,

                         CONSTRAINT fk_sancion_lector
                             FOREIGN KEY (id_lector)
                                 REFERENCES lector(id_lector)
);

CREATE TABLE auditoria (
                           id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           entidad_afectada VARCHAR(100) NOT NULL,
                           id_registro BIGINT NOT NULL,
                           accion VARCHAR(50) NOT NULL,
                           fecha_hora TIMESTAMP NOT NULL,
                           usuario_responsable VARCHAR(160) NOT NULL
);
