-- 1. Tabla ROL
CREATE TABLE rol (
                     id_rol      BIGINT GENERATED BY DEFAULT AS IDENTITY,
                     nombre_rol  VARCHAR(100) NOT NULL,
                     descripcion TEXT,
                     CONSTRAINT pk_rol PRIMARY KEY (id_rol)
);

-- 2. Tabla USUARIO
CREATE TABLE usuario (
                         id_usuario      BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         id_rol          BIGINT NOT NULL,
                         nombre_completo VARCHAR(160) NOT NULL,
                         credenciales    VARCHAR(255) NOT NULL,
                         estado          VARCHAR(20)  NOT NULL,
                         CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
                         CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES rol (id_rol)
);

-- 3. Tabla LECTOR
CREATE TABLE lector (
                        id_lector      BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        id_usuario     BIGINT NOT NULL,
                        nro_lector     VARCHAR(40) NOT NULL,
                        datos_contacto VARCHAR(255),
                        fecha_registro DATE NOT NULL,
                        CONSTRAINT pk_lector PRIMARY KEY (id_lector),
                        CONSTRAINT fk_lector_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
                        CONSTRAINT uq_lector_usuario UNIQUE (id_usuario),
                        CONSTRAINT uq_lector_nro UNIQUE (nro_lector)
);

-- 4. Tabla SANCION (Reemplaza a Multa)
CREATE TABLE sancion (
                         id_sancion   BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         id_lector    BIGINT NOT NULL,
                         fecha_inicio DATE NOT NULL,
                         fecha_final  DATE,
                         motivo       VARCHAR(250) NOT NULL,
                         estado       VARCHAR(20)  NOT NULL,
                         CONSTRAINT pk_sancion PRIMARY KEY (id_sancion),
                         CONSTRAINT fk_sancion_lector FOREIGN KEY (id_lector) REFERENCES lector (id_lector)
);

-- 5. Tabla EDITORIAL
CREATE TABLE editorial (
                           id_editorial BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           nombre       VARCHAR(160) NOT NULL,
                           CONSTRAINT pk_editorial PRIMARY KEY (id_editorial)
);

-- 6. Tabla AUTOR (Nueva)
CREATE TABLE autor (
                       id_autor     BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       nombre       VARCHAR(150) NOT NULL,
                       nacionalidad VARCHAR(100),
                       CONSTRAINT pk_autor PRIMARY KEY (id_autor)
);

-- 7. Tabla LIBRO (Se elimina el campo autor directo)
CREATE TABLE libro (
                       id_libro         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       id_editorial     BIGINT NOT NULL,
                       titulo           VARCHAR(220) NOT NULL,
                       categoria        VARCHAR(100),
                       anio_publicacion INTEGER,
                       CONSTRAINT pk_libro PRIMARY KEY (id_libro),
                       CONSTRAINT fk_libro_editorial FOREIGN KEY (id_editorial) REFERENCES editorial (id_editorial)
);

-- 8. Tabla LIBRO_AUTOR (Nueva - Relación N:M)
CREATE TABLE libro_autor (
                             id_libro BIGINT NOT NULL,
                             id_autor BIGINT NOT NULL,
                             CONSTRAINT pk_libro_autor PRIMARY KEY (id_libro, id_autor),
                             CONSTRAINT fk_la_libro FOREIGN KEY (id_libro) REFERENCES libro (id_libro),
                             CONSTRAINT fk_la_autor FOREIGN KEY (id_autor) REFERENCES autor (id_autor)
);

-- 9. Tabla EJEMPLAR (Nueva - Representa el libro físico)
CREATE TABLE ejemplar (
                          id_ejemplar   BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          id_libro      BIGINT NOT NULL,
                          codigo_barras VARCHAR(50) NOT NULL,
                          estado        VARCHAR(30) NOT NULL,
                          CONSTRAINT pk_ejemplar PRIMARY KEY (id_ejemplar),
                          CONSTRAINT fk_ejemplar_libro FOREIGN KEY (id_libro) REFERENCES libro (id_libro),
                          CONSTRAINT uq_ejemplar_codigo UNIQUE (codigo_barras)
);

-- 10. Tabla PRESTAMO (Ahora se vincula al EJEMPLAR físico, no al catálogo)
CREATE TABLE prestamo (
                          id_prestamo               BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          id_lector                 BIGINT NOT NULL,
                          id_ejemplar               BIGINT NOT NULL,
                          fecha_salida              DATE NOT NULL,
                          fecha_prevista_devolucion DATE NOT NULL,
                          fecha_devolucion_real     DATE,
                          estado                    VARCHAR(20) NOT NULL,
                          CONSTRAINT pk_prestamo PRIMARY KEY (id_prestamo),
                          CONSTRAINT fk_prestamo_lector FOREIGN KEY (id_lector) REFERENCES lector (id_lector),
                          CONSTRAINT fk_prestamo_ejemplar FOREIGN KEY (id_ejemplar) REFERENCES ejemplar (id_ejemplar)
);

-- 11. Tabla RENOVACION
CREATE TABLE renovacion (
                            id_renovacion        BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            id_prestamo          BIGINT NOT NULL,
                            fecha_renovacion     DATE NOT NULL,
                            nueva_fecha_prevista DATE NOT NULL,
                            CONSTRAINT pk_renovacion PRIMARY KEY (id_renovacion),
                            CONSTRAINT fk_renovacion_prestamo FOREIGN KEY (id_prestamo) REFERENCES prestamo (id_prestamo)
);

-- 12. Tabla RESERVA
CREATE TABLE reserva (
                         id_reserva          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         id_lector           BIGINT NOT NULL,
                         id_libro            BIGINT NOT NULL,
                         fecha_reserva       DATE NOT NULL,
                         fecha_limite_retiro DATE NOT NULL,
                         estado              VARCHAR(30) NOT NULL,
                         CONSTRAINT pk_reserva PRIMARY KEY (id_reserva),
                         CONSTRAINT fk_reserva_lector FOREIGN KEY (id_lector) REFERENCES lector (id_lector),
                         CONSTRAINT fk_reserva_libro FOREIGN KEY (id_libro) REFERENCES libro (id_libro)
);

-- 13. Tabla AUDITORIA (Nueva)
CREATE TABLE auditoria (
                           id_auditoria        BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           entidad_afectada    VARCHAR(100) NOT NULL,
                           id_registro         BIGINT NOT NULL,
                           accion              VARCHAR(50) NOT NULL,
                           fecha_hora          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           usuario_responsable VARCHAR(160) NOT NULL,
                           CONSTRAINT pk_auditoria PRIMARY KEY (id_auditoria)
);